url: 		'https://fantastic-chaja-c4fd8c.netlify.com'
baseurl: 	''
filesurl:       'https://fantastic-chaja-c4fd8c.netlify.com/files'
urlimg: 	'https://fantastic-chaja-c4fd8c.netlify.com/images'

# See › https://github.com/jekyll/jekyll-gist#disabling-noscript-support
gist:
  noscript: false

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  sourcemap: true

# Disable when not in production
google_analytics_tracking_id: false

# display future posts in PR previews
future: true